package engine

import (
	"crypto/ed25519"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/JGautam09/NeuroVSA/core"
)

// The sem field's compatibility contract, in both directions: packs signed before the
// field existed keep verifying byte-for-byte (canonical v1 form), while sem-carrying packs
// sign a distinct canonical form (v2) that cannot alias v1 — and the v4 memory image
// carries sem losslessly while rejecting v3 images outright.

func semTestKey() ed25519.PrivateKey {
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i)
	}
	return ed25519.NewKeyFromSeed(seed)
}

// TestV1SignedPackStillVerifies: the committed fixture was generated and signed by the
// PRE-sem engine (v0.8.1 code). Its signature must keep verifying forever — old packs in
// the wild (including the registry examples) must not be invalidated by the sem change.
func TestV1SignedPackStillVerifies(t *testing.T) {
	raw, err := os.ReadFile("testdata/signed_pack_v1.json")
	if err != nil {
		t.Fatal(err)
	}
	var p Pack
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatal(err)
	}
	if !p.VerifySignature() {
		t.Fatal("pre-sem signed pack no longer verifies — canonical v1 bytes drifted")
	}
	if got := string(p.CanonicalBytes()[:10]); got != "NVSA-PACK1" {
		t.Fatalf("sem-less pack canonicalizes as %q, want NVSA-PACK1", got)
	}
	if _, err := p.Memory(); err != nil {
		t.Fatalf("pre-sem pack failed to materialize: %v", err)
	}
}

// TestV3MemoryImageRejected: the committed v3 image (generated by the pre-sem engine) must
// be refused with a descriptive error, never misparsed — semantics cannot be reconstructed
// from display labels after the fact.
func TestV3MemoryImageRejected(t *testing.T) {
	raw, err := os.ReadFile("testdata/memory_image_v3.bin")
	if err != nil {
		t.Fatal(err)
	}
	m := NewAssociativeMemory()
	err = m.UnmarshalBinary(raw)
	if err == nil {
		t.Fatal("v3 memory image was accepted by the v4 loader")
	}
	if !strings.Contains(err.Error(), "version 3") {
		t.Fatalf("v3 rejection should name the version, got: %v", err)
	}
}

// TestSemPackSignAndTamper: a sem-carrying pack signs as canonical v2, and every forgery
// direction breaks the signature — tampered sem, stripped sem (v2→v1 downgrade), injected
// sem (v1→v2 upgrade), and tampered label.
func TestSemPackSignAndTamper(t *testing.T) {
	dict := core.NewSeededTokenDictionary(9)
	mem := NewAssociativeMemory()
	mem.SetVocabSeed(9)
	mem.SetSite(3)
	mem.StoreSemantic(dict.GetOrRegister("ctx"), dict.GetOrRegister("tgt"), "display label", `{"v":1,"claim":"x"}`)

	p := PackFromMemory("semmed", mem)
	if p.Entries[0].Sem == "" {
		t.Fatal("PackFromMemory dropped the sem field")
	}
	p.Sign(semTestKey())
	if !p.VerifySignature() {
		t.Fatal("signed sem pack must verify")
	}
	if got := string(p.CanonicalBytes()[:10]); got != "NVSA-PACK2" {
		t.Fatalf("sem pack canonicalizes as %q, want NVSA-PACK2", got)
	}

	tamperedSem := p
	tamperedSem.Entries = append([]PackEntry(nil), p.Entries...)
	tamperedSem.Entries[0].Sem = `{"v":1,"claim":"forged"}`
	if tamperedSem.VerifySignature() {
		t.Fatal("tampered sem still verifies")
	}

	stripped := p
	stripped.Entries = append([]PackEntry(nil), p.Entries...)
	stripped.Entries[0].Sem = ""
	if stripped.VerifySignature() {
		t.Fatal("sem-stripped pack still verifies — v2→v1 downgrade must break the signature")
	}

	tamperedLabel := p
	tamperedLabel.Entries = append([]PackEntry(nil), p.Entries...)
	tamperedLabel.Entries[0].Label = "other label"
	if tamperedLabel.VerifySignature() {
		t.Fatal("tampered label still verifies")
	}

	// Injection: sign a sem-less pack, then bolt a sem on.
	memPlain := NewAssociativeMemory()
	memPlain.SetVocabSeed(9)
	memPlain.SetSite(4)
	memPlain.StoreLabeled(dict.GetOrRegister("a"), dict.GetOrRegister("b"), "plain")
	q := PackFromMemory("plain", memPlain)
	q.Sign(semTestKey())
	if !q.VerifySignature() {
		t.Fatal("plain pack must verify")
	}
	q.Entries[0].Sem = `{"v":1,"claim":"injected"}`
	if q.VerifySignature() {
		t.Fatal("sem-injected pack still verifies — v1→v2 upgrade must break the signature")
	}
}

// TestSemWireAndImageRoundTrip: sem survives the JSON wire form and the v4 binary image
// bit-exactly, and fingerprints agree between the original and both round-trips.
func TestSemWireAndImageRoundTrip(t *testing.T) {
	dict := core.NewSeededTokenDictionary(11)
	mem := NewAssociativeMemory()
	mem.SetVocabSeed(11)
	mem.SetSite(5)
	sem := `{"v":1,"domain":"rulegarden","percept":{"sees":"food","dist":"near","dir":"N"},"action":"eat"}`
	mem.StoreSemantic(dict.GetOrRegister("p"), dict.GetOrRegister("a"), "food lesson", sem)
	mem.StoreLabeled(dict.GetOrRegister("q"), dict.GetOrRegister("b"), "sem-less neighbor")

	// Wire round-trip.
	p := PackFromMemory("rt", mem)
	raw, err := json.Marshal(p)
	if err != nil {
		t.Fatal(err)
	}
	var p2 Pack
	if err := json.Unmarshal(raw, &p2); err != nil {
		t.Fatal(err)
	}
	if p2.Entries[0].Sem != sem || p2.Entries[1].Sem != "" {
		t.Fatalf("sem did not survive the wire: %+v", p2.Entries)
	}

	// Image round-trip.
	img, err := mem.MarshalBinary()
	if err != nil {
		t.Fatal(err)
	}
	m2 := NewAssociativeMemory()
	if err := m2.UnmarshalBinary(img); err != nil {
		t.Fatal(err)
	}
	recs := m2.Ledger()
	if recs[0].Sem != sem || recs[1].Sem != "" {
		t.Fatalf("sem did not survive the image: %+v", recs)
	}
	if mem.Fingerprint() != m2.Fingerprint() || mem.LocalStateFingerprint() != m2.LocalStateFingerprint() {
		t.Fatal("image round-trip changed a fingerprint")
	}
}

// TestFingerprintAndMergeCoverSem: two memories identical except for one entry's sem must
// fingerprint differently (sem is future-relevant state — the P1-3 lesson), and merging
// them must refuse as a content collision rather than silently uniting divergent claims.
func TestFingerprintAndMergeCoverSem(t *testing.T) {
	build := func(sem string) *AssociativeMemory {
		dict := core.NewSeededTokenDictionary(13)
		m := NewAssociativeMemory()
		m.SetVocabSeed(13)
		m.SetSite(6)
		m.StoreSemantic(dict.GetOrRegister("x"), dict.GetOrRegister("y"), "same label", sem)
		return m
	}
	a := build(`{"v":1,"claim":"a"}`)
	b := build(`{"v":1,"claim":"b"}`)
	if a.Fingerprint() == b.Fingerprint() {
		t.Fatal("fingerprint ignores sem — two semantically different memories hash equal")
	}
	if _, err := a.Merge(b); err == nil || !strings.Contains(err.Error(), "different content") {
		t.Fatalf("merge of sem-divergent twins must refuse as a content collision, got %v", err)
	}

	// And sem rides through an honest merge.
	c := NewAssociativeMemory()
	c.SetVocabSeed(13)
	c.SetSite(7)
	if _, err := c.Merge(a); err != nil {
		t.Fatal(err)
	}
	if recs := c.Ledger(); recs[0].Sem != `{"v":1,"claim":"a"}` {
		t.Fatalf("merge dropped sem: %+v", recs)
	}
}

// TestPackMemoryRejectsOversizedSem: MaxSemLen is enforced at the untrusted pack boundary.
func TestPackMemoryRejectsOversizedSem(t *testing.T) {
	p := Pack{Name: "big", VocabSeed: 1, Site: 1, Entries: []PackEntry{{
		Seq: 1, Label: "l", Sem: strings.Repeat("x", MaxSemLen+1),
	}}}
	if _, err := p.Memory(); err == nil || !strings.Contains(err.Error(), "sem exceeding") {
		t.Fatalf("oversized sem must be rejected at materialization, got %v", err)
	}
}
